# Generated by Django 4.0.5 on 2022-06-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='expiryTime',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 16, 10, 15, 393225)),
        ),
        migrations.AddField(
            model_name='pool',
            name='minAmount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pool',
            name='applicationIndex',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
