# Generated by Django 4.0.5 on 2022-06-13 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pool_expirytime_pool_minamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderMnemonic', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=100)),
                ('applicationIndex', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='pool',
            name='expiryTime',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 20, 23, 20, 947300)),
        ),
    ]
