# Generated by Django 4.0.5 on 2022-06-13 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fund_alter_pool_expirytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='applicationIndex',
        ),
        migrations.AlterField(
            model_name='pool',
            name='expiryTime',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 20, 44, 19, 913603)),
        ),
    ]
